---
name: Molecule
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
      - uses: gofrolist/molecule-action@v2
